### ISSUE TITLE
APIでhtmlに関するタグを追加しても文字列として出力される

### ISSUE THREAD

**Issue by Puton1221** [Daichimarukana/uwuzu#2]
### 発生している問題について
apiに関するファイル全般で、htmlタグがそのまんま文字列として出力されている。

#### 入力
```php
<?php
   $msg = "こんにちは"
?>

<p><?php echo $msg ?></p>
```
#### 出力
```html
<p>こんにちは</p>
```

この問題により現在Websocketは対応していないが、調べたところ以下の二つの点が解決策となる可能性が大いにあることを示している。

### 解決策その1
`.htaccess`フォルダに以下のコードを追加し、htmlファイル内でphpを動作させる。
```
<FilesMatch "\.html$">
  AddType application/x-httpd-php .html
</FilesMatch>
```
この方法はApacheの動作設定でhtmlファイルの中にあるphpタグを認識し、使用できるようにするものであり、楽な方法である。

### 解決策その2
htmlに関するタグを`echo`で出力する。
どうやら、phpファイルにhtmlタグを追加しても、プレーンテキストとして扱うとのこと。したがって現在の動作は正常な動作であり、phpの仕様によるものである。
```php
<?php
   echo <<< EOM
   <p>Hi</p>
   EOM;
?>
```
この方法は現在のコードを破壊することなく出力することができるため、こちらを使用する方がいいこともある．

**Comment by Daichimarukana** [comment]
わかんないけど多分治ったんじゃない？
時間たったし...
ね...？
